export const GET_STYLES = "GET_STYLES";
export const UPDT_BOXSHADOW = "UPDT_BOXSHADOW";
export const UPDT_BORDERRADIUS = "UPDT_BORDERRADIUS";
export const UPDT_BORDERS = "UPDT_BORDERS";
export const UPDT_BASE = "UPDT_BASE";
